<?php

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

use MageOS\Blog\ViewModel\Post\Listing as PostListing;
use MageOS\Blog\ViewModel\Product\RelatedPosts;

/** @var RelatedPosts $viewModel */
$viewModel = $block->getData('view_model');
/** @var PostListing $listingViewModel */
$listingViewModel = $block->getData('listing_view_model');
$posts = $viewModel->getPosts();
?>
<?php if ($posts !== []): ?>
    <div class="mageos-blog-related-posts mageos-blog-cards">
        <?php foreach ($posts as $post): ?>
            <?= $block->getLayout()
                ->createBlock(\Magento\Framework\View\Element\Template::class)
                ->setTemplate('MageOS_Blog::post/card.phtml')
                ->setData('post', $post)
                ->setData('view_model', $listingViewModel)
                ->toHtml(); ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
